write a program to demonstrate the use of try catch block with the argument as an integer and string using multiple catch blocks
#include <iostream>
#include <string>

int main() {
    try {
        
        int num;
        std::cout << "Enter an integer: ";
        std::cin >> num;

        if (std::cin.fail()) {
            throw "Invalid input. Please enter an integer.";
        }

        
        std::string str;
        std::cout << "Enter a string: ";
        std::cin >> str;

        if (str.empty()) {
            throw std::string("String cannot be empty.");
        }

    } catch (const char* msg) {
        std::cerr << "Error: " << msg << std::endl;
    } catch (const std::string& msg) {
        std::cerr << "Error: " << msg << std::endl;
    } catch (...) {
        std::cerr << "An unknown error occurred." << std::endl;
    }

    return 0;
}
